##############################################################################
# For more information on parameters, refer to: 
# https://docs.gramaddict.org/#/configuration?id=configuration-file
#
# Note: be sure to comment out any parameters not used by adding a # in front
# AGAIN: YOU DON'T HAVE TO DELETE THE LINE, BUT ONLY COMMENT IT WITH A #!
##############################################################################
# General Configuration
##############################################################################

username: daily # you have to put your IG name here!
device: localhost:5555 # 'adb devices' in the console to know it.  It's needed only if you have more than 1 device connected
app-id: com.instagram.android
use-cloned-app: false
allow-untested-ig-version: false # Using an untested version of IG would cause unexpected behavior because some elements in the user interface may have been changed
screen-sleep: true
screen-record: false
speed-multiplier: 5
debug: false
close-apps: false
kill-atx-agent: false
restart-atx-agent: false
disable-block-detection: false
disable-filters: false
dont-type: false
# scrape-to-file: scraped.txt
total-crashes-limit: 7
count-app-crashes: false
shuffle-jobs: true
truncate-sources: 2-5

##############################################################################
# Actions
##############################################################################

## Interaction (active jobs)
blogger-followers: [ s.y_motivation_, wolf_motivation.il, ildailymotivation, ildailysuccess, growing.il, ilmotivation, ]
# blogger-following: [ username1, username2 ]
blogger-post-likers: [  s.y_motivation_, wolf_motivation.il, ildailymotivation, ildailysuccess, growing.il, ilmotivation, ]
blogger: [ yomedia_official, ]
hashtag-likers-top: [ מוטיבציה, מוטיבציהישראל, מוטיבציהיומית, הצלחה, הצלחהעסקית, הצלחהותוצאות ]
hashtag-likers-recent: [ מוטיבציה, מוטיבציהישראל, מוטיבציהיומית, הצלחה, הצלחהעסקית, הצלחהותוצאות ]
# hashtag-posts-top: [ hashtag1, hashtag2 ]
# hashtag-posts-recent: [ hashtag1, hashtag2 ]
# place-posts-top: [ place1, place2 ]
# place-posts-recent: [ place1, place2 ]
# place-likers-top: [ place1, place2 ]
# place-likers-recent: [ place1, place2 ]
# interact-from-file: [users.txt , usernames2.txt 3, usernames2.txt 10-15]
# posts-from-file: [posts.txt,]
feed: 3-12 # is the number of likes you will give in feed
likes-from-file: [urls.txt 1-7,]

## Special modifier for jobs and sources
watch-video-time: 15-35
watch-photo-time: 3-4
# can-reinteract-after: 48 # the amount of hours that have to pass from the last interaction
delete-interacted-users: true

## Unfollow (unfollow jobs)
unfollow: 10-20
# unfollow-any: 10-20
unfollow-non-followers: 10-20
# unfollow-any-non-followers: 10-20
# unfollow-any-followers: 10-20
# unfollow-from-file: [usernames1.txt 7-15, usernames2.txt 6]

## Special modifier for unfollow jobs
sort-followers-newest-to-oldest: false
unfollow-delay: 10-15

## Remove followers (active jobs)
remove-followers-from-file: [remove1.txt 5-10, remove2.txt 6]

## Special modifier for remove followers
delete-removed-followers: true

## Post Processing
# analytics: false # no more supported
telegram-reports: true # for using telegram-reports you have also to configure telegram.yml in your account folder

## Special actions
# pre-script: pre_script_path_here
# post-script: post_script_path_here

##############################################################################
# Source Limits
##############################################################################

interactions-count: 30-40
likes-count: 1-3
likes-percentage: 87-95
stories-count: 1-2
stories-percentage: 30-40
carousel-count: 2-3
carousel-percentage: 60-70
max-comments-pro-user: 0
comment-percentage: 0
# pm-percentage: 30-40
interact-percentage: 30-40
follow-percentage: 30-40
follow-limit: 4-5
skipped-list-limit: 10-15
skipped-posts-limit: 5
fling-when-skipped: 0
min-following: 137

##############################################################################
# Total Limits Per Session
##############################################################################

total-likes-limit: 50-70
total-follows-limit: 10-20
total-unfollows-limit: 10-20
total-watches-limit: 120-150
total-successful-interactions-limit: 120-150
total-interactions-limit: 280-300
total-comments-limit: 3-5
total-pm-limit: 3-5
total-scraped-limit: 100-150

##############################################################################
# Ending Session Conditions
##############################################################################

end-if-likes-limit-reached: true
end-if-follows-limit-reached: true
end-if-watches-limit-reached: false
end-if-comments-limit-reached: false
end-if-pm-limit-reached: false

##############################################################################
# Scheduling
##############################################################################

working-hours: [07.15-10.05, 12.26-14.30, 17.20-18.36, 21.15-23.46]
time-delta: 10-15
repeat: 90-280
# total-sessions: 2-3 # -1 or commented for infinite sessions
